version: '3.5'

services:
  es:
    build:
      context: .
    ports:
      - 3500:3500
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    networks:
      - coyote

networks:
  coyote:
    name: coyote
