version: '3.5'

services:
  es:
    image: node:13-alpine
    working_dir: /app/build
    command:
    - "node"
    - "-r"
    - "ts-node/register"
    - "/app/src/app.ts"
    ports:
      - 3500:3500
    volumes:
      - .:/app
    tty: true
    networks:
      - coyote

networks:
  coyote:
    name: coyote
